---
apiVersion: v1
kind: Namespace
metadata:
  name: rancher-vcluster
---
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: rancher-vcluster
  namespace: rancher-vcluster
  labels:
    addon.harvesterhci.io/experimental: "true"
spec:
  enabled: false
  repo: https://charts.loft.sh
  version: "v0.19.0"
  chart: vcluster
  valuesContent: |-
    # vCluster 0.19.0 configuration for Harvester v1.6.x
    # Root-level hostname required by Harvester webhook
    hostname: rancher.hvst-vip.aegisgroup.ch

    # Sync ingresses to host cluster and set correct service CIDR
    syncer:
      extraArgs:
        - --sync=ingresses
        - --service-cidr=10.53.0.0/16

    # K3s distribution
    vcluster:
      image: rancher/k3s:v1.31.4-k3s1
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 200m
          memory: 256Mi

    # Deploy manifests on init
    init:
      manifests: |-
        apiVersion: v1
        kind: Namespace
        metadata:
          name: cattle-system
        ---
        apiVersion: v1
        kind: Namespace
        metadata:
          name: cert-manager
          labels:
            certmanager.k8s.io/disable-validation: "true"
        ---
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: cert-manager
          namespace: kube-system
        spec:
          targetNamespace: cert-manager
          repo: https://charts.jetstack.io
          chart: cert-manager
          version: v1.17.1
          helmVersion: v3
          set:
            crds.enabled: "true"
        ---
        apiVersion: helm.cattle.io/v1
        kind: HelmChart
        metadata:
          name: rancher
          namespace: kube-system
        spec:
          targetNamespace: cattle-system
          repo: https://releases.rancher.com/server-charts/latest
          chart: rancher
          version: v2.13.0
          set:
            ingress.tls.source: rancher
            hostname: rancher.hvst-vip.aegisgroup.ch
            replicas: 1
            global.cattle.psp.enabled: "false"
            bootstrapPassword: admin123123!
          helmVersion: v3
