---
apiVersion: v1
kind: Namespace
metadata:
  name: rancher-vcluster
---
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: rancher-vcluster
  namespace: rancher-vcluster
  labels:
    addon.harvesterhci.io/experimental: "true"
spec:
  enabled: false
  repo: https://charts.loft.sh
  version: "v0.30.0"
  chart: vcluster
  valuesContent: |-
    # NOTE: vCluster 0.30.0 has strict schema validation.
    # Custom values must be hardcoded in manifestsTemplate below.
    # Edit the following values in the HelmChart spec:
    #   - hostname: your Rancher URL (must resolve to Harvester VIP)
    #   - version: Rancher version to deploy
    #   - bootstrapPassword: initial admin password

    sync:
      toHost:
        ingresses:
          enabled: true

    controlPlane:
      distro:
        k3s:
          enabled: true
          image:
            registry: ""
            repository: "rancher/k3s"
            tag: "v1.31.4-k3s1"
          securityContext: {}
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 40m
              memory: 64Mi
      backingStore:
        database:
          embedded:
            enabled: true

      statefulSet:
        image:
          registry: "ghcr.io"
          repository: "loft-sh/vcluster-pro"
          tag: "0.30.0"
        resources:
          limits:
            ephemeral-storage: 10Gi
            memory: 4Gi
          requests:
            ephemeral-storage: 1Gi
            cpu: 200m
            memory: 256Mi

    experimental:
      deploy:
        vcluster:
          manifestsTemplate: |-
            apiVersion: v1
            kind: Namespace
            metadata:
              name: cattle-system
            ---
            apiVersion: v1
            kind: Namespace
            metadata:
              name: cert-manager
              labels:
                certmanager.k8s.io/disable-validation: "true"
            ---
            apiVersion: helm.cattle.io/v1
            kind: HelmChart
            metadata:
              name: cert-manager
              namespace: kube-system
            spec:
              targetNamespace: cert-manager
              repo: https://charts.jetstack.io
              chart: cert-manager
              version: v1.17.1
              helmVersion: v3
              set:
                crds.enabled: "true"
            ---
            apiVersion: helm.cattle.io/v1
            kind: HelmChart
            metadata:
              name: rancher
              namespace: kube-system
            spec:
              targetNamespace: cattle-system
              repo: https://releases.rancher.com/server-charts/latest
              chart: rancher
              # =====================================================
              # CONFIGURE THESE VALUES BEFORE ENABLING THE ADDON
              # =====================================================
              version: v2.13.0
              set:
                ingress.tls.source: rancher
                # REQUIRED: Set to your Rancher hostname (must resolve to Harvester VIP)
                hostname: rancher.example.com
                replicas: 1
                global.cattle.psp.enabled: "false"
                # REQUIRED: Set your initial admin password
                bootstrapPassword: admin
              helmVersion: v3
